### ISSUE TITLE
pre-commit cannot modify files

### ISSUE THREAD

**Issue by jonas-eschle** [FlamingTempura/bibtex-tidy#409]
Hi there, and thanks for the package!

However, I struggle to make it run in pre-commit: using the "--modify" flag, it errors with
--modify/-m is only valid when specifying input files

That's how I am using it
```
  - repo: https://github.com/FlamingTempura/bibtex-tidy
    rev: "v1.11.0"
    hooks:
      - id: bibtex-tidy
        args: ["--modify"]
        files: ^bib/.*bib
```

The files expression works and gives files, I've tested that with another "echo" hook.
Any ideas?

**Comment by FlamingTempura** [comment]
Fixed in v1.14.0 - the following should work
```yaml
repos:
-   repo: https://github.com/FlamingTempura/bibtex-tidy
    rev: v1.14.0
    hooks:
    -   id: bibtex-tidy
        files: ^bib/.*bib
```
