### ISSUE TITLE
Specifying `args` in `pre-commit-config.yaml` causes no formatting (and no output)

### ISSUE THREAD

**Issue by 34j** [FlamingTempura/bibtex-tidy#419]
```yml
repos:
  - repo: https://github.com/FlamingTempura/bibtex-tidy
    rev: v1.11.0
    hooks:
      - id: bibtex-tidy
        args: [--no-align]
```
```shell
pre-commit run -a
```
![image](https://github.com/FlamingTempura/bibtex-tidy/assets/55338215/e314364e-c567-4ec6-a0ff-d901fa22a5ab)
However, the file is not formatted.
If `args` is not specified, it works perfectly.
Simlar: #409, Related: #14

**Comment by artpelling** [comment]
Facing the same problem..

**Comment by artpelling** [comment]
I've tried to find out what happens, did not really get to the bottom of it. I am now using version `1.9.0` as a workaround which works as expected.

**Comment by 34j** [comment]
You are right, I tried it and confirmed that it does not work with 1.10.0 and works with 1.9.0.
I have also tried the CLI, and the following commands seem to work correctly and could not determine the cause.
```shell
npx -g install bibtex-tidy
bibtex-tidy --no-align test.bib
bibtex-tidy test.bib --no-align
bibtex-tidy "test.bib" "--no-align"   
```

**Comment by flying-sheep** [comment]
I stepped into pre-commit, and the command being run is

```
('~/.cache/pre-commit/reponbqhr4ak/node_env-default/bin/node', '~/.cache/pre-commit/reponbqhr4ak/node_env-default/bin/bibtex-tidy', '--omit=abstract', '--curly', '--space=4', '--align=13', '--sort=key', '--duplicates=key,doi', '--no-escape', '--sort-fields', '--trailing-commas', 'docs/references.bib')
```

So the problem is that bibtex-tidy doesn’t parse its command line arguments correctly when run using `node path/to/bibtex-tidy ...args`.

**Comment by FlamingTempura** [comment]
Fixed in v1.14.0 - the following should work:
```yaml
repos:
-   repo: https://github.com/FlamingTempura/bibtex-tidy
    rev: v1.14.0
    hooks:
    -   id: bibtex-tidy
        args: ['--align=10', '--curly']
```
