### ISSUE TITLE
Github Actions Integration?

### ISSUE THREAD

**Issue by simonprovost** [FlamingTempura/bibtex-tidy#464]
Hi @FlamingTempura !

I love BibTex Tidy!  Thank you so much.

I was wondering how we could use it in a Github Actions workflow.  I tried installing NPM and running the normal bibtex-tidy CLI, but it does not appear to modify the input file.  I tried using --v2 and specifying an output file; it removed the input file but did not add anything to the new file; strange, right? 

I wondered if there was a limitation with Github workflows perhaps? 

Cheers

```yaml
...

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install bibtex-tidy
        run: npm install -g bibtex-tidy

...

      - name: Run bibtex-tidy on biblio.bib
        run: bibtex-tidy --v2 --output $GITHUB_WORKSPACE/thesis/biblio.bib --curly --numeric --months --tab --sort=-year,author --duplicates=key,doi --drop-all-caps --sort-fields --strip-comments --encode-urls --remove-empty-fields --no-remove-dupe-fields $GITHUB_WORKSPACE/thesis/biblio.bib

      - name: Check if biblio.bib changed
        run: git diff --exit-code $GITHUB_WORKSPACE/thesis/biblio.bib || echo "biblio.bib was modified"

...
```

With an example
```bib
@article{Hoare1978,
	Author = {Thomas M. J. Fruchterman and Edward and Edward M. Reingold},
	Date-Added = {2008-03-23 18:13:21 +0000},
	Date-Modified = {2008-03-23 18:13:21 +0000},
	Journal = {Communications of the ACM},
	Month = aug,
	Number = 8,
	Pages = {666-677},
	Title = {Communicating Sequential Processes},
	Volume = 21,
	Year = 1978
}
```

Git Diff Output example:
```
--- a/thesis/biblio.bib
+++ b/thesis/biblio.bib
@@ -1,12 +1 @@
-@article{Hoare19[7](https://github.com/simonprovost/thesis/actions/runs/15620555184/job/44004075292#step:12:8)8,
-	Author = {Thomas M. J. Fruchterman and Edward and Edward M. Reingold},
-	Date-Added = {200[8](https://github.com/simonprovost/thesis/actions/runs/15620555184/job/44004075292#step:12:9)-03-23 18:13:21 +0000},
-	Date-Modified = {2008-03-23 18:13:21 +0000},
-	Journal = {Communications of the ACM},
-	Month = aug,
-	Number = 8,
-	Pages = {666-677},
-	Title = {Communicating Sequential Processes},
-	Volume = 21,
-	Year = 1[9](https://github.com/simonprovost/thesis/actions/runs/15620555184/job/44004075292#step:12:10)78
-}
+
```

Cheers
